<?php

namespace App\Services;

use Illuminate\Support\Facades\File;

class SnuffleupagusService
{
    protected static string $configPath = '/etc/php.d/snuffleupagus.rules';
    protected static string $globalConfig = '/usr/local/openpanel/.conf/snuffleupagus.json';

    public static function isInstalled(): bool
    {
        $output = ShellService::exec('php -m 2>/dev/null | grep -i snuffleupagus');
        return !empty(trim($output));
    }

    public static function install(): array
    {
        $output = ShellService::exec('pecl install snuffleupagus 2>&1');
        if (stripos($output, 'install ok') !== false || stripos($output, 'successfully') !== false) {
            self::enableModule();
            return ['success' => true, 'message' => 'Snuffleupagus installed.', 'output' => $output];
        }
        return ['success' => false, 'message' => 'Installation failed.', 'output' => $output];
    }

    public static function getConfig(): array
    {
        if (!file_exists(self::$globalConfig)) {
            return self::getDefaultConfig();
        }
        return json_decode(file_get_contents(self::$globalConfig), true) ?: self::getDefaultConfig();
    }

    public static function saveConfig(array $data): array
    {
        File::ensureDirectoryExists(dirname(self::$globalConfig));
        file_put_contents(self::$globalConfig, json_encode($data, JSON_PRETTY_PRINT));
        self::generateRules($data);
        return ['success' => true, 'message' => 'Snuffleupagus configuration saved.'];
    }

    public static function getRules(): string
    {
        if (!file_exists(self::$configPath)) {
            return '';
        }
        return file_get_contents(self::$configPath);
    }

    public static function saveRules(string $rules): array
    {
        file_put_contents(self::$configPath, $rules);
        ShellService::exec('systemctl restart php-fpm 2>/dev/null');
        return ['success' => true, 'message' => 'Rules saved and PHP-FPM restarted.'];
    }

    public static function generateRules(array $config): void
    {
        $rules = "; Snuffleupagus rules - Generated by OpenPanel\n";
        $rules .= "; " . date('Y-m-d H:i:s') . "\n\n";

        if ($config['cookie_encrypt'] ?? false) {
            $rules .= "sp.cookie.name.regex(\"/^(session|csrf)$/s\");\n";
            $rules .= "sp.cookie.encrypt();\n\n";
        }

        if ($config['disable_xxe'] ?? true) {
            $rules .= "sp.disable_function.function('simplexml_load_string').param('data').value_r('<!ENTITY').drop();\n";
            $rules .= "sp.disable_function.function('simplexml_load_file').param('filename').value_r('<!ENTITY').drop();\n\n";
        }

        if ($config['disable_eval'] ?? false) {
            $rules .= "sp.disable_function.function('eval').drop();\n\n";
        }

        if ($config['disable_exec'] ?? false) {
            $rules .= "sp.disable_function.function('exec').drop();\n";
            $rules .= "sp.disable_function.function('system').drop();\n";
            $rules .= "sp.disable_function.function('passthru').drop();\n";
            $rules .= "sp.disable_function.function('shell_exec').drop();\n\n";
        }

        if ($config['global_strict'] ?? false) {
            $rules .= "sp.global_strict.enable();\n\n";
        }

        if ($config['allow_broken'] ?? false) {
            $rules .= "sp.allow_broken_configuration.enable();\n\n";
        }

        $customRules = $config['custom_rules'] ?? '';
        if ($customRules) {
            $rules .= "\n; Custom rules\n{$customRules}\n";
        }

        file_put_contents(self::$configPath, $rules);
    }

    protected static function enableModule(): void
    {
        $iniContent = "extension=snuffleupagus.so\nsp.configuration_file=" . self::$configPath . "\n";
        file_put_contents('/etc/php.d/99-snuffleupagus.ini', $iniContent);
    }

    protected static function getDefaultConfig(): array
    {
        return [
            'enabled' => true,
            'cookie_encrypt' => true,
            'disable_xxe' => true,
            'disable_eval' => false,
            'disable_exec' => false,
            'global_strict' => false,
            'allow_broken' => false,
            'custom_rules' => '',
        ];
    }
}
