<?php

return [

    'name' => env('OPENPANEL_NAME', 'OpenPanel'),
    'version' => env('OPENPANEL_VERSION', '1.0.0'),

    'paths' => [
        'home' => env('OPENPANEL_HOME', '/home'),
        'panel_root' => env('OPENPANEL_ROOT', '/usr/local/openpanel'),
        'nginx_conf' => env('OPENPANEL_NGINX_CONF', '/etc/nginx'),
        'nginx_user_conf' => env('OPENPANEL_NGINX_USER_CONF', '/etc/nginx/conf.d/users'),
        'php_fpm_conf' => env('OPENPANEL_PHP_FPM_CONF', '/etc/php-fpm.d'),
        'php_fpm_user_conf' => env('OPENPANEL_PHP_FPM_USER_CONF', '/etc/php-fpm.d/users'),
        'dns_zone_dir' => env('OPENPANEL_DNS_ZONE_DIR', '/var/named'),
        'named_conf' => env('OPENPANEL_NAMED_CONF', '/etc/named.conf'),
        'postfix_main_cf' => env('OPENPANEL_POSTFIX_MAIN_CF', '/etc/postfix/main.cf'),
        'postfix_vhost' => env('OPENPANEL_POSTFIX_VHOST', '/etc/postfix/vhost'),
        'postfix_transport' => env('OPENPANEL_POSTFIX_TRANSPORT', '/etc/postfix/transport'),
        'dovecot_conf' => env('OPENPANEL_DOVECOT_CONF', '/etc/dovecot/dovecot.conf'),
        'ssh_config' => env('OPENPANEL_SSH_CONFIG', '/etc/ssh/sshd_config'),
        'php_ini' => env('OPENPANEL_PHP_INI', '/etc/php.ini'),
        'named_conf_dir' => env('OPENPANEL_NAMED_CONF_DIR', '/etc'),
        'letsencrypt_live' => env('OPENPANEL_LETSENCRYPT_LIVE', '/etc/letsencrypt/live'),
        'csf_conf' => env('OPENPANEL_CSF_CONF', '/etc/csf/csf.conf'),
        'modsec_dir' => env('OPENPANEL_MODSEC_DIR', '/etc/nginx/modsec'),
        'ssl_certs' => env('OPENPANEL_SSL_CERTS', '/etc/pki/tls/certs'),
        'ssl_private' => env('OPENPANEL_SSL_PRIVATE', '/etc/pki/tls/private'),
        'roundcube' => env('OPENPANEL_ROUNDCUBE', '/usr/local/openpanel/services/roundcube'),
        'phpmyadmin' => env('OPENPANEL_PHPMYADMIN', '/usr/local/openpanel/services/phpmyadmin'),
        'backup_dir' => env('OPENPANEL_BACKUP_DIR', '/backup'),
        'log_dir' => env('OPENPANEL_LOG_DIR', '/var/log/openpanel'),
        'cron_dir' => env('OPENPANEL_CRON_DIR', '/var/spool/cron'),
        'mail_log' => env('OPENPANEL_MAIL_LOG', '/var/log/maillog'),
        'apache_conf' => env('OPENPANEL_APACHE_CONF', '/usr/local/apache/conf'),
        'tomcat_home' => env('OPENPANEL_TOMCAT_HOME', '/var/lib/tomcat'),
        'opendkim_dir' => env('OPENPANEL_OPENDKIM_DIR', '/etc/opendkim'),
    ],

    'services' => [
        'nginx' => 'nginx',
        'php_fpm' => 'php-fpm',
        'mariadb' => 'mariadb',
        'named' => 'named',
        'postfix' => 'postfix',
        'dovecot' => 'dovecot',
        'pure_ftpd' => 'pure-ftpd',
        'sshd' => 'sshd',
        'crond' => 'crond',
        'openpanel_nginx' => 'openpanel-nginx',
        'openpanel_php_fpm' => 'openpanel-php-fpm',
        'tomcat' => 'tomcat',
        'varnish' => 'varnish',
        'monit' => 'monit',
        'opendkim' => 'opendkim',
        'clamav' => 'clamd@amavisd',
        'csf' => 'csf',
        'iptables' => 'iptables',
        'redis' => 'redis',
        'memcached' => 'memcached',
    ],

    'ports' => [
        'user_http' => (int) env('OPENPANEL_PORT_USER_HTTP', 2082),
        'user_https' => (int) env('OPENPANEL_PORT_USER_HTTPS', 2083),
        'admin_http' => (int) env('OPENPANEL_PORT_ADMIN_HTTP', 2086),
        'admin_https' => (int) env('OPENPANEL_PORT_ADMIN_HTTPS', 2087),
        'webmail_http' => (int) env('OPENPANEL_PORT_WEBMAIL_HTTP', 2095),
        'webmail_https' => (int) env('OPENPANEL_PORT_WEBMAIL_HTTPS', 2096),
        'user_website' => (int) env('OPENPANEL_PORT_WEBSITE', 80),
    ],

    'defaults' => [
        'shell' => '/bin/bash',
        'php_version' => '8.3',
        'webserver' => 'nginx',
        'package' => 'default',
        'dns_template' => 'default',
        'mail_spool_size' => '500M',
        'backup_retention_days' => 7,
        'max_login_attempts' => 5,
        'login_lockout_minutes' => 15,
    ],

    'security' => [
        'blocked_shells' => [
            'rm -rf /',
            'mkfs',
            'dd if=',
            ':(){',
            'fork bomb',
            '> /dev/sda',
            'chmod -R 777 /',
            'wget -O- | sh',
            'curl -sSL | sh',
            'wget -O- | bash',
            'curl -sSL | bash',
        ],
        'max_command_length' => 1000,
        'command_timeout' => 30,
        'audit_shell_commands' => env('OPENPANEL_AUDIT_SHELL', true),
        'log_file' => env('OPENPANEL_AUDIT_LOG', '/var/log/openpanel/audit.log'),
    ],

    'supported_php_versions' => ['8.1', '8.2', '8.3', '8.4'],

    'dns' => [
        'default_ttl' => 3600,
        'default_refresh' => 3600,
        'default_retry' => 1800,
        'default_expire' => 604800,
        'default_minimum' => 86400,
    ],

    'mail' => [
        'max_quota_mb' => 1024,
        'default_quota_mb' => 250,
        'spam_score_threshold' => 5.0,
    ],

    'packages' => [
        'default' => [
            'max_wordpress_sites' => 5,
            'max_staging_sites' => 1,
            'max_backups' => 5,
            'backup_retention_days' => 7,
            'max_php_memory' => 512,
            'max_php_fpm_children' => 20,
            'redis_allowed' => true,
            'varnish_allowed' => true,
            'staging_allowed' => true,
            'clone_allowed' => true,
            'performance_profiles' => ['safe_default', 'high_traffic', 'woocommerce', 'membership', 'development'],
        ],
        'starter' => [
            'max_wordpress_sites' => 1,
            'max_staging_sites' => 0,
            'max_backups' => 3,
            'backup_retention_days' => 3,
            'max_php_memory' => 256,
            'max_php_fpm_children' => 5,
            'redis_allowed' => false,
            'varnish_allowed' => false,
            'staging_allowed' => false,
            'clone_allowed' => false,
            'performance_profiles' => ['safe_default'],
        ],
        'business' => [
            'max_wordpress_sites' => 10,
            'max_staging_sites' => 3,
            'max_backups' => 10,
            'backup_retention_days' => 14,
            'max_php_memory' => 1024,
            'max_php_fpm_children' => 50,
            'redis_allowed' => true,
            'varnish_allowed' => true,
            'staging_allowed' => true,
            'clone_allowed' => true,
            'performance_profiles' => ['safe_default', 'high_traffic', 'woocommerce', 'membership', 'development'],
        ],
        'enterprise' => [
            'max_wordpress_sites' => 50,
            'max_staging_sites' => 10,
            'max_backups' => 30,
            'backup_retention_days' => 30,
            'max_php_memory' => 2048,
            'max_php_fpm_children' => 100,
            'redis_allowed' => true,
            'varnish_allowed' => true,
            'staging_allowed' => true,
            'clone_allowed' => true,
            'performance_profiles' => ['safe_default', 'high_traffic', 'woocommerce', 'membership', 'development'],
        ],
    ],

];
